# Generated by Django 4.2.6 on 2023-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='firstname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='lastname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='otp',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='phone_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
